datagrid:
    active_invoice_grid:
        title: Active Invoices
        icon: check
        source:
            repository: 'SolidInvoiceInvoiceBundle:Invoice'
            method: getGridQuery
        properties:
            route: '_invoices_view'
        columns:
            id:
                key: id
                label: ID
                editable: false
                cell: integer
            status:
                key: status
                label: Status
                editable: false
                cell: invoice_status
            client:
                key: client
                label: Client
                editable: false
                cell: client
            total:
                key: total
                label: Total
                editable: false
                cell: money
                formatter: money
            tax:
                key: tax
                label: Tax
                editable: false
                cell: money
                formatter: money
            discount:
                key: discount
                label: Discount
                editable: false
                cell: discount
            created:
                key: created
                label: Created
                editable: false
                cell: date
        search:
            fields:
                - status
                - total
                - c.name
        line_actions:
            view:
                icon: eye
                label: invoice.grid.actions.view
                route: _invoices_view
                route_params:
                    id: id
            edit:
                icon: edit
                label: invoice.grid.actions.edit
                route: _invoices_edit
                route_params:
                    id: id
        actions:
            archive:
                label: Archive
                icon: archive
                confirm: 'Are you sure you want to archive the selected rows?'
                action: invoice_grid_archive
                className: warning
            delete:
                label: Delete
                icon: ban
                confirm: 'Are you sure you want to delete the selected rows?'
                action: invoice_grid_delete
                className: danger
    archive_invoice_grid:
        title: Archived Invoices
        icon: archive
        source:
            repository: 'SolidInvoiceInvoiceBundle:Invoice'
            method: getArchivedGridQuery
        properties:
            route: '_invoices_view'
        columns:
            id:
                key: id
                label: ID
                editable: false
                cell: integer
            status:
                key: status
                label: Status
                editable: false
                cell: invoice_status
            client:
                key: client
                label: Client
                editable: false
                cell: client
            total:
                key: total
                label: Total
                editable: false
                cell: string
            tax:
                key: tax
                label: Tax
                editable: false
                cell: string
            discount:
                key: discount
                label: Discount
                editable: false
                cell: string
                formatter: discount
            created:
                key: created
                label: Created
                editable: false
                cell: date
        search:
            fields:
                - status
                - total
                - c.name
        actions:
            delete:
                label: Delete
                icon: ban
                confirm: 'Are you sure you want to delete the selected rows?'
                action: invoice_grid_delete
                className: danger
    recurring_invoice_grid:
        title: Recurring Invoices
        icon: sync-alt
        source:
            repository: 'SolidInvoiceInvoiceBundle:RecurringInvoice'
            method: getRecurringGridQuery
        properties:
            route: '_invoices_view_recurring'
        columns:
            id:
                key: id
                label: ID
                editable: false
                cell: integer
            status:
                key: status
                label: Status
                editable: false
                cell: invoice_status
            client:
                key: client
                label: Client
                editable: false
                cell: client
            total:
                key: total
                label: Total
                editable: false
                cell: money
                formatter: money
            tax:
                key: tax
                label: Tax
                editable: false
                cell: money
                formatter: money
            discount:
                key: discount
                label: Discount
                editable: false
                cell: string
                formatter: discount
            dateStart:
                key: dateStart
                label: 'Start Date'
                editable: false
                cell: recurringInvoiceStart
            dateEnd:
                key: dateEnd
                label: 'End Date'
                editable: false
                cell: recurringInvoiceEnd
            frequency:
                key: frequency
                label: Frequency
                editable: false
                cell: recurringInvoiceFrequency
            created:
                key: created
                label: Created
                editable: false
                cell: date
        search:
            fields:
                - status
                - total
                - c.name
        line_actions:
            view:
                icon: eye
                label: invoice.grid.actions.view
                route: _invoices_view
                route_params:
                    id: id
            edit:
                icon: edit
                label: invoice.grid.actions.edit
                route: _invoices_edit_recurring
                route_params:
                    id: id
        actions:
            archive:
                label: Archive
                icon: archive
                confirm: 'Are you sure you want to archive the selected rows?'
                action: invoice_grid_recurring_archive
                className: warning
            delete:
                label: Delete
                icon: ban
                confirm: 'Are you sure you want to delete the selected rows?'
                action: invoice_grid_recurring_delete
                className: danger
    archive_recurring_invoice_grid:
        title: Archived Recurring Invoices
        icon: archive
        source:
            repository: 'SolidInvoiceInvoiceBundle:RecurringInvoice'
            method: getArchivedGridQuery
        properties:
            route: '_invoices_view_recurring'
        columns:
            id:
                key: id
                label: ID
                editable: false
                cell: integer
            status:
                key: status
                label: Status
                editable: false
                cell: invoice_status
            client:
                key: client
                label: Client
                editable: false
                cell: client
            total:
                key: total
                label: Total
                editable: false
                cell: money
                formatter: money
            tax:
                key: tax
                label: Tax
                editable: false
                cell: money
                formatter: money
            discount:
                key: discount
                label: Discount
                editable: false
                cell: string
                formatter: discount
            dateStart:
                key: dateStart
                label: 'Start Date'
                editable: false
                cell: recurringInvoiceStart
            dateEnd:
                key: dateEnd
                label: 'End Date'
                editable: false
                cell: recurringInvoiceEnd
            frequency:
                key: frequency
                label: Frequency
                editable: false
                cell: recurringInvoiceFrequency
            created:
                key: created
                label: Created
                editable: false
                cell: date
        search:
            fields:
                - status
                - total
                - c.name
        actions:
            delete:
                label: Delete
                icon: ban
                confirm: 'Are you sure you want to delete the selected rows?'
                action: invoice_grid_recurring_delete
                className: danger
