datagrid:
    active_quote_grid:
        title: Active Quotes
        icon: check
        source:
            repository: 'SolidInvoiceQuoteBundle:Quote'
            method: getGridQuery
        properties:
            route: '_quotes_view'
        columns:
            id:
                key: id
                label: ID
                editable: false
                cell: integer
            status:
                key: status
                label: Status
                editable: false
                cell: quote_status
            client:
                key: client
                label: Client
                editable: false
                cell: client
            total:
                key: total
                label: Total
                editable: false
                cell: money
                formatter: money
            tax:
                key: tax
                label: Tax
                editable: false
                cell: money
                formatter: money
            discount:
                key: discount
                label: Discount
                editable: false
                cell: string
                formatter: discount
            created:
                key: created
                label: Created
                editable: false
                cell: date
        search:
            fields:
                - status
                - total
                - c.name
        line_actions:
            view:
                icon: eye
                label: quote.grid.actions.view
                route: _quotes_view
                route_params:
                    id: id
            edit:
                icon: edit
                label: quote.grid.actions.edit
                route: _quotes_edit
                route_params:
                    id: id
        actions:
            archive:
                label: Archive
                icon: archive
                confirm: 'Are you sure you want to archive the selected rows?'
                action: quote_grid_archive
                className: warning
            delete:
                label: Delete
                icon: ban
                confirm: 'Are you sure you want to delete the selected rows?'
                action: quote_grid_delete
                className: danger
    archive_quote_grid:
        title: Archived Quotes
        icon: archive
        source:
            repository: 'SolidInvoiceQuoteBundle:Quote'
            method: getArchivedGridQuery
        properties:
            route: '_quotes_view'
        columns:
            id:
                key: id
                label: ID
                editable: false
                cell: integer
            status:
                key: status
                label: Status
                editable: false
                cell: quote_status
            client:
                key: client
                label: Client
                editable: false
                cell: client
            total:
                key: total
                label: Total
                editable: false
                cell: string
            tax:
                key: tax
                label: Tax
                editable: false
                cell: string
            discount:
                key: discount
                label: Discount
                editable: false
                cell: string
                formatter: discount
            created:
                key: created
                label: Created
                editable: false
                cell: date
        search:
            fields:
                - status
                - total
                - c.name
        actions:
            delete:
                label: Delete
                icon: ban
                confirm: 'Are you sure you want to delete the selected rows?'
                action: quote_grid_delete
                className: danger
